### ISSUE TITLE
slidev v0.40.3 下无法运行

### ISSUE THREAD

**Issue by Tao-JiaJun** [isaaccaa/slidev-theme-prussianblue#2]
在slidev 0.40.3下报错，0.39.0下运行正常。
```bash
[postcss] /Users/maxxie/workspace/slidev/br/node_modules/slidev-theme-prussianblue/styles/layout.css?v=7ebf2b5f:2:6: Unknown word
[postcss] /Users/maxxie/workspace/slidev/br/node_modules/slidev-theme-prussianblue/styles/layout.css?v=7ebf2b5f:2:6: Unknown word (x2)
13:37:50 [vite] Internal server error: [postcss] /Users/maxxie/workspace/slidev/br/node_modules/slidev-theme-prussianblue/styles/layout.css?v=7ebf2b5f:2:6: Unknown word
  Plugin: vite:css
  File: /Users/maxxie/workspace/slidev/br/node_modules/slidev-theme-prussianblue/styles/layout.css?v=7ebf2b5f:2:6
  1  |  :root {
  2  |    // default theme color
     |        ^
  3  |    // can be overrided by uses `themeConfig` option
  4  |    --slidev-theme-primary: #5d8392;
      at Input.error (/Users/maxxie/workspace/slidev/br/node_modules/postcss/lib/input.js:148:16)
      at Parser.unknownWord (/Users/maxxie/workspace/slidev/br/node_modules/postcss/lib/parser.js:540:22)
      at Parser.decl (/Users/maxxie/workspace/slidev/br/node_modules/postcss/lib/parser.js:219:16)
      at Parser.other (/Users/maxxie/workspace/slidev/br/node_modules/postcss/lib/parser.js:128:18)
      at Parser.parse (/Users/maxxie/workspace/slidev/br/node_modules/postcss/lib/parser.js:72:16)
      at parse (/Users/maxxie/workspace/slidev/br/node_modules/postcss/lib/parse.js:11:12)
      at new LazyResult (/Users/maxxie/workspace/slidev/br/node_modules/postcss/lib/lazy-result.js:133:16)
      at Processor.process (/Users/maxxie/workspace/slidev/br/node_modules/postcss/lib/processor.js:28:14)
      at compileCSS (file:///Users/maxxie/workspace/slidev/br/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-9912c491.js:36731:14)
      at async TransformContext.transform (file:///Users/maxxie/workspace/slidev/br/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-9912c491.js:36195:56)
      at async Object.transform (file:///Users/maxxie/workspace/slidev/br/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-9912c491.js:41662:30)
      at async loadAndTransform (file:///Users/maxxie/workspace/slidev/br/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-9912c491.js:39467:29)
[postcss] /Users/maxxie/workspace/slidev/br/node_modules/slidev-theme-prussianblue/styles/layout.css?v=7ebf2b5f:2:6: Unknown word
```

**Comment by TheoCUC** [comment]
您好～可能是在slidev0.40版本后修改了css的格式验证要求什么的，请更新主题，新版已修复～
